domain: b-a-b-i-s.github.io               # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://b-a-b-i-s.github.io          # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /jekyll-tutorial-completed      # place folder name if the site is served in a subfolder

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

